### ISSUE TITLE
Disposable amount is calculated incorrectly and can become negative

### ISSUE THREAD

**Issue by Bargsteen** [Concordium/concordium-reference-wallet-android#150] opened 2022-05-19 08:49 UTC
**Bug Description**
The disposable amount is calculated incorrectly, and it can become negative.
I assume this is because the calculation used is `disposable = total - scheduled - delegated`, but the scheduled amount can be delegated and then it is subtracted twice.

**Steps to Reproduce**
1. Use account `A` with e.g. `1000` CCD
2. Send `600` CCD with a schedule to `A`
3. Delegate `1500` CCD before the scheduled CCD are released (thereby delegating some of the scheduled CCD)
4. Look at the disposable amount

**Expected Result**
The disposable amount should be `~100` CCD.

**Actual Result**
The disposable amount is negative: `- ~500`.

**Versions**
- Software Version: 3.0.0 (84)
- OS: Android
- Mobile device: Huawei

**Comment by rimbi** [comment] 2022-06-21 06:11
The test could not be verified.

**Expected Result**
The disposable amount should be `~100` CCD.

**Actual Result**
The disposable amount is negative: `0` CCD.

**Comment by XOOPsoft** [comment] 2022-06-21 06:26
@jens-concordium
@rimbi 
I have talked to Jens Ager about this. If you have a public balance of 1000 CCD and then receive 600 in a released scheduled. Then you have 1600 in public balance, but there is still only 1000 at disposal for fees and for sending CCD to someone.
So if you stake 1500, then you have staked the 1000 from your at disposal and 500 from your release schedule. It means that there is 0 CCD left in your at disposal.
Is is possible for you to attach a screenshot?
@jens-concordium - can you confirm if it's correct or not?

**Comment by rimbi** [comment] 2022-06-21 06:28
That's not what I get from my conversations with the team. What do you think @mh-concordium and @td202 ?

**Comment by jens-concordium** [comment] 2022-06-21 06:33
@rimbi @XOOPsoft It stakes the locked amounts first. So in this example it will stake the 600 in the release schedule, and then 900 from the unlocked public balance, leaving 100 at disposal.

**Comment by XOOPsoft** [comment] 2022-06-21 06:43
@rimbi @jens-concordium 
I have talked to Jens Ager again. I will correct this issue. Thanks!

**Comment by jens-concordium** [comment] 2022-06-21 06:45
Yep, this was my mistake! I had given @XOOPsoft incorrect information in the first place.

**Comment by mh-concordium** [comment] 2022-06-21 06:51
Two cases to test:

1. If you have staked/delegated your 500 CCDs that were at disposal, you will end up with 0 at disposal and 500 staked. Then, afterwards you receive 500 CCDs via scheduled transfer, you should have 500 at disposal because those which are scheduled should be staked/delegated first.
2. If you have 500 CCDs at disposal and 500 CCDs scheduled, if you delegate 900, you should have 100 at disposal (- tx fee).

**Comment by mh-concordium** [comment] 2022-06-21 07:23
@Niljak could you please implement the same for iOS?

**Comment by XOOPsoft** [comment] 2022-06-21 09:46
For the mentioned test cases. What should be displayed at the top of the "Sends funds" page for total and at disposal?
And which amount should be filled in, when using the "Send all" button?

**Comment by mh-concordium** [comment] 2022-06-22 05:42
@XOOPsoft, this page seems to be working fine. Why do you ask?

![image](https://user-images.githubusercontent.com/98821384/174952090-725d091c-bd37-43c3-be38-748149b89389.png)

**Comment by XOOPsoft** [comment] 2022-06-22 05:56
So there is no difference to "at disposal" if a scheduled amount is created before or after setting up delegation?

**Comment by mh-concordium** [comment] 2022-06-22 07:10
Good question, it actually matters. As written in test case 1:
If you have staked/delegated your 500 CCDs that were at disposal, you will end up with 0 at disposal and 500 staked. Then, afterwards you receive 500 CCDs via scheduled transfer, you should have 500 at disposal because those which are scheduled should be staked/delegated first. 

I have just confirmed that behavior with Concordium Client.

**Comment by XOOPsoft** [comment] 2022-06-22 11:08
Fixed in version 3.0.0 (97)
(notice the version-number, it has been decided that only build-number will be increased for the release, not the 3.0.0)

**Comment by rimbi** [comment] 2022-06-22 11:55
There is something wrong with the balance calculation:

![Photo on 22 06 2022 at 14 52](https://user-images.githubusercontent.com/51825/175022755-cb29db48-1622-4566-8c07-09212477cf0f.jpg)

Either `Balance total` should be `~1500` or `total currently at disposal` be `~100` 

verified with version 3.0.0 (97)

**Comment by rimbi** [comment] 2022-06-23 06:02
verified with release 3.0.0 (98)

**Closed** 2022-08-08 06:39 UTC
Labels: [Prio] High, [Type] Bug, [Sev] Critical
