### ISSUE TITLE
Delegation: The status page

### ISSUE THREAD

**Issue by jens-concordium** [Concordium/concordium-reference-wallet-android#115] opened 2022-03-02 08:57 UTC
**Task description**
As a part of the delegation implementation in the Concordium Mobile Wallet, we are going to need a status page, that will allow the user to inspect their current delegation. 

As it can be seen in Flow 1 in Figma, the delegation status page can be entered via the burger menu of the specific account pages. There are two different scenarios in this context:
- Scenario 1, where the account is not already delegating. In this case the burger menu will also show a baking option, and it the user presses the Delegation option, they will be met with a carousel explaining delegation, before they enter the status page.  
- Scenario 2, where the account already has an active delegation. In this case only the delegation button is shown, and the carousel is not shown at this point. Additionally, in scenario 2 it can be seen on the specific account screen, how much is currently delegated with either an open pool, or with the L-pool. 

<br/>
<br/>

As it can be seen in Flow 6 in Figma, the status page can have different states, depending on the current delegation status. 

1. A state with no current delegation (Can also be seen in context in Flow 1)
2. A state awaiting a delegation transaction to finalize (Can also be seen in context in Delegation status scenario 1)
3. A state with a "regular" status, with no pending changes (Can also be seen in context in Delegation status scenario 1)
4. A state with with a pending decrease in delegation amount, meaning the amount cannot be touched for the cooldown period, and the delegation cannot be stopped. (Can also be seen in context in Delegation status scenario 2)
5. A state with a pending stop of the delegation, meaning the amount cannot be touched for the cooldown period, and the delegation cannot be stopped again. (Can also be seen in context in Delegation status scenario 4)
6. A state where the baker pool is in a "shut down" cool down period, so the user can see a message about this.
7. A state where a delegation transaction failed, hence the user is shown an error message. (Can also be seen in context in Delegation status scenario 1)

<br/>
<br/>

**The complete list of what information can be found in the delegation status:**
- Delegating account (Name + account address)
- Delegation amount (Amount of CCD delegated)
- Target baker pool (the baker ID of the pool)
- "Rewards will be" (Added to stake | Added to delegation amount)

If there are pending changes, the message "The following changes will take effect in approximately XX days" will be shown at the bottom, follow by either:

- New delegation amount (the new delegation amount)

or

- "The delegation will be stopped, and the delegation amount will be unlocked on the public balance of the account. "

And lastly, if the target bool is in cool down to close down, the following message will be displayed:

- "This pool has been deregistered, and will stop baking after it’s cool down has ended in <amount of time>"

**Comment by XOOPsoft** [comment] 2022-06-02 09:58
@mh-concordium
It is the app uses estimatedChangeTime
estimatedChangeTime is not implemented in the example you provided.

See the wallet proxy documentation:
https://github.com/Concordium/concordium-wallet-proxy#baker-pool-status

The docs says that pendingChangeType for RemovePool should look like this:
{
    "pendingChangeType": "RemovePool",
    "effectiveTime": "2022-03-31T23:54:48.25Z"
    "estimatedChangeTime": "2022-04-01T06:00:00.0Z"
}

**Comment by mh-concordium** [comment] 2022-06-02 10:28
This is Stagenet from this morning. App version 3.0.5(89).

I think that estimatedChangeTime is returned by wallet proxy and what I am referring to is the time I got as a response from client by querying my node on Stagenet. I don't think that proxy returns all the same responses as node interface. 

In any case, my point is that the pool 155 is closing - going to be removed and thats why I have pointed to the time, to prove that the pool is going to be closed. At the same time there is no notification for the delegator that the pool will be closed and thats what this issue is about. 

Once we will have visible text in UI that is implemented as in Figma Flow 6: Different status screen scenarios, Status 6, then, we could determine if the time is correct or not.

Does it make any sense?

**Comment by XOOPsoft** [comment] 2022-06-02 10:38
On staging it looks like estimatedChangeTime has been put inside a pendingChangeDetails element. It is not how the docs are, so the app have not implemented it with this extra pendingChangeDetails level. I have asked Ales if we should change the or he will change the wallet proxy.
Here is an example from this endpoint: https://wallet-proxy.stagenet.concordium.com/v0/bakerPool/112
{"allPoolTotalCapital":"15016306005979","bakerAddress":"3czRFBf2AH7SzbxGCkd65P5dFP4PuXPLgTSxcRVRykGgqxMErN","bakerEquityCapital":"200000000","bakerId":112,"bakerStakePendingChange":{"pendingChangeDetails":{"effectiveTime":"2022-06-02T10:44:34.25Z","estimatedChangeTime":"2022-06-02T10:56:01Z"},"pendingChangeType":"RemovePool"},"currentPaydayStatus":{"bakerEquityCapital":"200000000","blocksBaked":0,"delegatedCapital":"290000000","effectiveStake":"490000000","finalizationLive":false,"lotteryPower":3.2645394923904305e-5,"transactionFeesEarned":"0"},"delegatedCapital":"290000000","delegatedCapitalCap":"400000000","poolInfo":{"commissionRates":{"bakingCommission":0.1,"finalizationCommission":1.0,"transactionCommission":0.2},"metadataUrl":"","openStatus":"openForAll"},"poolType":"BakerPool"}

**Comment by abizjak** [comment] 2022-06-02 13:54
I will change the implementation to conform to the README.

**Comment by mkmks** [comment] 2022-06-20 12:08
I can confirm that states 1-6 are correctly implemented, the state 7 is still to be tested.

**Comment by mkmks** [comment] 2022-06-21 09:36
When trying to make a failing transaction I noticed that changing the delegator pool to a closed pool results in submitting a transaction (which will fail), but choosing a delegator pool for an account without active delegation isn't possible: entering a baker id of a closed pool on the "Update delegation" screen results in a hint that the pool is closed.

Perhaps, it's a bug, and the "Update delegation" screen behaviour should be identical in both cases: a hint should be given and no transaction made if it's known that the chosen pool is closed.

**Comment by mh-concordium** [comment] 2022-06-21 09:55
How did you make this transaction? If I try to update current delegation -> insert the pool id of a closed pool, UI validation doesn't let me to select Continue.

**Comment by mkmks** [comment] 2022-06-21 11:30
I had an account delegating to a pool. Then I did 'Delegation -> Update current delegation', and on the 'Update delegation' screen I entered a baker id of a closed pool. UI validation didn't prevent me from submitting a transaction (it's hash was `bac3b816`).

**Comment by mkmks** [comment] 2022-06-21 11:45
It's working correctly in 3.0.11 after all.

**Closed** 2022-08-08 06:41 UTC
Labels: [Prio] High, [Type] Task
